### PR TITLE
Fix required to allow compilation with PlatformIO

### PR DESCRIPTION
**Pull request by frankonski**
Without this fix, projects using PlatformIO fails to compile.

### CODE REVIEW

**Comment by HomeSpan** [comment]
Can you remind me what error message you get when compiling under PlatformIO?  I'm curious why no one else has had this issue.

**Comment by frankonski** [comment]
This is the full compilation output:
```
 *  Executing task: C:\Users\frankonski\.platformio\penv\Scripts\platformio.exe run --environment keeyes-esp32dev 

Processing keeyes-esp32dev (platform: espressif32; board: esp32dev; framework: arduino)
----------------------------------------------------------------------------------------------------------------------
Verbose mode can be enabled via `-v, --verbose` option
Build git commit: 9a75bfe-dirty
HomeSpan git commit: 1.1.2-1437-g2d47aab-dirty
CONFIGURATION: https://docs.platformio.org/page/boards/espressif32/esp32dev.html
PLATFORM: Espressif 32 (51.3.0-x-stable) > Espressif ESP32 Dev Module
HARDWARE: ESP32 240MHz, 320KB RAM, 4MB Flash
DEBUG: Current (cmsis-dap) External (cmsis-dap, esp-bridge, esp-prog, iot-bus-jtag, jlink, minimodule, olimex-arm-usb-ocd, olimex-arm-usb-ocd-h, olimex-arm-usb-tiny-h, olimex-jtag-tiny, tumpa)
PACKAGES: 
 - framework-arduinoespressif32 @ 3.0.7+sha.3bfa3e0 
 - framework-arduinoespressif32-libs @ 5.1.0+sha.632e0c2a9f 
 - tool-esptoolpy @ 4.8.1 
 - tool-mklittlefs @ 3.2.0 
 - tool-openocd-esp32 @ 2.1100.20220706 (11.0) 
 - tool-riscv32-esp-elf-gdb @ 12.1.0+20221002 
 - tool-xtensa-esp-elf-gdb @ 12.1.0+20221002 
 - toolchain-xtensa-esp32 @ 12.2.0+20230208
LDF: Library Dependency Finder -> https://bit.ly/configure-pio-ldf
LDF Modes: Finder ~ chain, Compatibility ~ soft
Found 41 compatible libraries
Scanning dependencies...
Dependency Graph
|-- HomeSpan @ 2.0.0
Building in release mode
Compiling .pio\build\keeyes-esp32dev\src\main.cpp.o
Building .pio\build\keeyes-esp32dev\bootloader.bin
Generating partitions .pio\build\keeyes-esp32dev\partitions.bin
Compiling .pio\build\keeyes-esp32dev\lib9c3\ESPmDNS\ESPmDNS.cpp.o
esptool.py v4.8.1.1
Creating esp32 image...
Merged 1 ELF section
Successfully created esp32 image.
Compiling .pio\build\keeyes-esp32dev\lib3c4\Network\NetworkClient.cpp.o
Compiling .pio\build\keeyes-esp32dev\lib3c4\Network\NetworkEvents.cpp.o
Compiling .pio\build\keeyes-esp32dev\lib3c4\Network\NetworkInterface.cpp.o
Compiling .pio\build\keeyes-esp32dev\lib3c4\Network\NetworkManager.cpp.o
Compiling .pio\build\keeyes-esp32dev\lib3c4\Network\NetworkServer.cpp.o
Compiling .pio\build\keeyes-esp32dev\lib3c4\Network\NetworkUdp.cpp.o
Compiling .pio\build\keeyes-esp32dev\lib2ba\Update\HttpsOTAUpdate.cpp.o
Compiling .pio\build\keeyes-esp32dev\lib2ba\Update\Updater.cpp.o
Compiling .pio\build\keeyes-esp32dev\lib175\ArduinoOTA\ArduinoOTA.cpp.o
Compiling .pio\build\keeyes-esp32dev\lib4e1\WiFi\AP.cpp.o
Compiling .pio\build\keeyes-esp32dev\lib4e1\WiFi\STA.cpp.o
Archiving .pio\build\keeyes-esp32dev\lib9c3\libESPmDNS.a
Compiling .pio\build\keeyes-esp32dev\lib4e1\WiFi\WiFi.cpp.o
Compiling .pio\build\keeyes-esp32dev\lib4e1\WiFi\WiFiAP.cpp.o
Compiling .pio\build\keeyes-esp32dev\lib4e1\WiFi\WiFiGeneric.cpp.o
Compiling .pio\build\keeyes-esp32dev\lib4e1\WiFi\WiFiMulti.cpp.o
Compiling .pio\build\keeyes-esp32dev\lib4e1\WiFi\WiFiSTA.cpp.o
Archiving .pio\build\keeyes-esp32dev\lib2ba\libUpdate.a
Compiling .pio\build\keeyes-esp32dev\lib4e1\WiFi\WiFiScan.cpp.o
Compiling .pio\build\keeyes-esp32dev\libca5\HomeSpan\HAP.cpp.o
Archiving .pio\build\keeyes-esp32dev\lib3c4\libNetwork.a
Compiling .pio\build\keeyes-esp32dev\libca5\HomeSpan\HKDF.cpp.o
Compiling .pio\build\keeyes-esp32dev\libca5\HomeSpan\HomeSpan.cpp.o
Archiving .pio\build\keeyes-esp32dev\lib175\libArduinoOTA.a
Compiling .pio\build\keeyes-esp32dev\libca5\HomeSpan\Network.cpp.o
Compiling .pio\build\keeyes-esp32dev\libca5\HomeSpan\SRP.cpp.o
Compiling .pio\build\keeyes-esp32dev\libca5\HomeSpan\TLV8.cpp.o
Compiling .pio\build\keeyes-esp32dev\libca5\HomeSpan\Utils.cpp.o
Compiling .pio\build\keeyes-esp32dev\libca5\HomeSpan\src\extras\Blinker.cpp.o
lib/HomeSpan/src/Network.cpp:30:10: fatal error: DNSServer.h: No such file or directory

*******************************************************************
* Looking for DNSServer.h dependency? Check our library registry!
*
* CLI  > platformio lib search "header:DNSServer.h"
* Web  > https://registry.platformio.org/search?q=header:DNSServer.h
*
*******************************************************************

   30 | #include <DNSServer.h>
      |          ^~~~~~~~~~~~~
compilation terminated.
*** [.pio\build\keeyes-esp32dev\libca5\HomeSpan\Network.cpp.o] Error 1
============================================ [FAILED] Took 13.37 seconds ============================================

 *  The terminal process "C:\Users\frankonski\.platformio\penv\Scripts\platformio.exe 'run', '--environment', 'keeyes-esp32dev'" terminated with exit code: 1. 
 *  Terminal will be reused by tasks, press any key to close it. 
 ```
and this is my `platformio.ini` file:
```
[env:keeyes-esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
platform_packages=
  platformio/framework-arduinoespressif32 @ https://github.com/espressif/arduino-esp32.git#3.0.7
  platformio/framework-arduinoespressif32-libs @ https://github.com/espressif/esp32-arduino-lib-builder/releases/download/idf-release_v5.1/esp32-arduino-libs-idf-release_v5.1-632e0c2a.zip
#lib_deps = homespan/HomeSpan@^1.9.0
monitor_port = COM3
# Now required because since arduino-esp32 3.x is larger
board_build.partitions = min_spiffs.csv
upload_protocol = espota
upload_port = mezzanine.local
upload_flags = --auth=homespan-ota
monitor_speed = 115200

extra_scripts = 
    pre:src/getGitCommit.py
```

**Comment by frankonski** [comment]
One thing to note is that I have HomeSpan's source in the `lib` folder as a git submodule, and `main.cpp` sits in `src`.
```
frankonski@inspiron MINGW64 ~/Documents/PlatformIO/Projects/LightStrip (dev)
$ find . -type d -not -path "./.git*" -not -path "./lib/HomeSpan/examples*" -not -path "./lib/HomeSpan/.git*" -not -path "./.pio*"
.
./.vscode
./include
./lib
./lib/HomeSpan
./lib/HomeSpan/docs
./lib/HomeSpan/docs/images
./lib/HomeSpan/docs/StepperDrivers
./lib/HomeSpan/documents
./lib/HomeSpan/src
./lib/HomeSpan/src/src
./lib/HomeSpan/src/src/extras
./lib/HomeSpan/tools
./src
./test
```

**Comment by HomeSpan** [comment]
Thanks for the details.  This doesn't seem to be a linking error:  PIO is claiming it cannot find the DNSServer.h file.  If that's true, it means the file is missing.  But if it's missing, how come it does find the file when the link as added to HomeSpan.cpp (which does not use DNSServer at all)?

Did this error just start occurring when you moved HomeSpan 2.X (which is based on IDF5)?  If so, I think this means something is amiss in your PIO setup.  Have you tried posting the issue to the PIO discussion boards?  Even though your fix may address the issue, it could easily come up again as the code continues to migrate and it would probably be best to sort this out and get to the root cause.

**Comment by frankonski** [comment]
Your comment got me thinking. Unfortunately, PlatformIO does not yet support esp32-arduino v3 [source](https://github.com/platformio/platform-espressif32/issues/1225).. but there are workarounds as I have used above.

Nevertheless, running a verbose build (to see all of the IncludePath) showed the dependency graph, which PlatformIO uses to create its build command.
Using the unmodified HomeSpan.cpp (without `#include <DNSServer.h`), I could see the following dependency graph:
```
LDF: Library Dependency Finder -> https://bit.ly/configure-pio-ldf
LDF Modes: Finder ~ chain, Compatibility ~ soft
Found 41 compatible libraries
Scanning dependencies...
Dependency Graph
|-- HomeSpan @ 2.0.0 (License: Unknown, Path: C:\Users\frankonski\Documents\PlatformIO\Projects\LightStrip\lib\HomeSpan)
|   |-- ESPmDNS @ 3.0.7 (License: Unknown, Path: C:\Users\frankonski\.platformio\packages\framework-arduinoespressif32\libraries\ESPmDNS)
|   |-- ArduinoOTA @ 3.0.7 (License: Unknown, Path: C:\Users\frankonski\.platformio\packages\framework-arduinoespressif32\libraries\ArduinoOTA)
|   |   |-- Networking @ 3.0.7 (License: Unknown, Path: C:\Users\frankonski\.platformio\packages\framework-arduinoespressif32\libraries\Network)
|   |   |-- Update @ 3.0.7 (License: Unknown, Path: C:\Users\frankonski\.platformio\packages\framework-arduinoespressif32\libraries\Update)
|   |   |-- ESPmDNS @ 3.0.7 (License: Unknown, Path: C:\Users\frankonski\.platformio\packages\framework-arduinoespressif32\libraries\ESPmDNS)
|   |-- WiFi @ 3.0.7 (License: Unknown, Path: C:\Users\frankonski\.platformio\packages\framework-arduinoespressif32\libraries\WiFi)
|   |   |-- Networking @ 3.0.7 (License: Unknown, Path: C:\Users\frankonski\.platformio\packages\framework-arduinoespressif32\libraries\Network)
Building in release mode
```

When adding `#include <DNSServer.h>` to HomeSpan.cpp, it then printed this:
```
LDF: Library Dependency Finder -> https://bit.ly/configure-pio-ldf
LDF Modes: Finder ~ chain, Compatibility ~ soft
Found 41 compatible libraries
Scanning dependencies...
Dependency Graph
|-- HomeSpan @ 2.0.0 (License: Unknown, Path: C:\Users\frankonski\Documents\PlatformIO\Projects\LightStrip\lib\HomeSpan)
|   |-- ESPmDNS @ 3.0.7 (License: Unknown, Path: C:\Users\frankonski\.platformio\packages\framework-arduinoespressif32\libraries\ESPmDNS)
|   |-- ArduinoOTA @ 3.0.7 (License: Unknown, Path: C:\Users\frankonski\.platformio\packages\framework-arduinoespressif32\libraries\ArduinoOTA)
|   |   |-- Networking @ 3.0.7 (License: Unknown, Path: C:\Users\frankonski\.platformio\packages\framework-arduinoespressif32\libraries\Network)
|   |   |-- Update @ 3.0.7 (License: Unknown, Path: C:\Users\frankonski\.platformio\packages\framework-arduinoespressif32\libraries\Update)
|   |   |-- ESPmDNS @ 3.0.7 (License: Unknown, Path: C:\Users\frankonski\.platformio\packages\framework-arduinoespressif32\libraries\ESPmDNS)
|   |-- DNSServer @ 3.0.7 (License: Unknown, Path: C:\Users\frankonski\.platformio\packages\framework-arduinoespressif32\libraries\DNSServer)
|   |   |-- ESP32 Async UDP @ 3.0.7 (License: Unknown, Path: C:\Users\frankonski\.platformio\packages\framework-arduinoespressif32\libraries\AsyncUDP)
|   |   |-- WiFi @ 3.0.7 (License: Unknown, Path: C:\Users\frankonski\.platformio\packages\framework-arduinoespressif32\libraries\WiFi)
|   |   |   |-- Networking @ 3.0.7 (License: Unknown, Path: C:\Users\frankonski\.platformio\packages\framework-arduinoespressif32\libraries\Network)
|   |-- WiFi @ 3.0.7 (License: Unknown, Path: C:\Users\frankonski\.platformio\packages\framework-arduinoespressif32\libraries\WiFi)
|   |   |-- Networking @ 3.0.7 (License: Unknown, Path: C:\Users\frankonski\.platformio\packages\framework-arduinoespressif32\libraries\Network)
Building in release mode
```
As you can see above, PIO added DNSServer as a dependency to HomeSpan.

Then that bit.ly link points to https://docs.platformio.org/en/latest/librarymanager/ldf.html

The solution was to simply add `lib_ldf_mode = deep` to my `platformio.ini` file, which produced a differently ordered dependency graph, but allowed successful compilation:
```
LDF: Library Dependency Finder -> https://bit.ly/configure-pio-ldf
LDF Modes: Finder ~ deep, Compatibility ~ soft
Found 41 compatible libraries
Scanning dependencies...
Dependency Graph
|-- HomeSpan @ 2.0.0 (License: Unknown, Path: C:\Users\frankonski\Documents\PlatformIO\Projects\LightStrip\lib\HomeSpan)
|   |-- ESPmDNS @ 3.0.7 (License: Unknown, Path: C:\Users\frankonski\.platformio\packages\framework-arduinoespressif32\libraries\ESPmDNS)
|   |-- WiFi @ 3.0.7 (License: Unknown, Path: C:\Users\frankonski\.platformio\packages\framework-arduinoespressif32\libraries\WiFi)
|   |   |-- Networking @ 3.0.7 (License: Unknown, Path: C:\Users\frankonski\.platformio\packages\framework-arduinoespressif32\libraries\Network)
|   |-- DNSServer @ 3.0.7 (License: Unknown, Path: C:\Users\frankonski\.platformio\packages\framework-arduinoespressif32\libraries\DNSServer)
|   |   |-- WiFi @ 3.0.7 (License: Unknown, Path: C:\Users\frankonski\.platformio\packages\framework-arduinoespressif32\libraries\WiFi)
|   |   |   |-- Networking @ 3.0.7 (License: Unknown, Path: C:\Users\frankonski\.platformio\packages\framework-arduinoespressif32\libraries\Network)
|   |   |-- ESP32 Async UDP @ 3.0.7 (License: Unknown, Path: C:\Users\frankonski\.platformio\packages\framework-arduinoespressif32\libraries\AsyncUDP)
|   |-- ArduinoOTA @ 3.0.7 (License: Unknown, Path: C:\Users\frankonski\.platformio\packages\framework-arduinoespressif32\libraries\ArduinoOTA)
|   |   |-- ESPmDNS @ 3.0.7 (License: Unknown, Path: C:\Users\frankonski\.platformio\packages\framework-arduinoespressif32\libraries\ESPmDNS)
|   |   |-- Networking @ 3.0.7 (License: Unknown, Path: C:\Users\frankonski\.platformio\packages\framework-arduinoespressif32\libraries\Network)
|   |   |-- Update @ 3.0.7 (License: Unknown, Path: C:\Users\frankonski\.platformio\packages\framework-arduinoespressif32\libraries\Update)
Building in release mode
```

Is it possible that in the refactoring you did in HS 2.x, the inclusion of `DNSServer.h` was done in a different place?

**Comment by HomeSpan** [comment]
I just re-checked 1.9.1 and no changes at all to anything related to DNSServer when I moved to 2.0.0.  The `#include <DNSServer.h>` and all the calls are exclusively in Network.cpp.

**Comment by frankonski** [comment]
I found what caused the change (I think): rename of `Network.h` to `Network_HS.h` without its respective .cpp file.
I don't know the exact reason why you renamed your own `Network.h` to `Network_HS.h`, but by simply renaming `Network.cpp` to `Network_HS.cpp`, I was then able to recompile the dev branch without `lib_ldf_mode = deep`.

I don't know how PIO creates its dependency graph, but I think the mismatch of the basename (Network.cpp / Network_HS.h) causes PIO to miss including Network_HS.h altogether.

Here is the dependency graph when I renamed `Network.cpp` to `Network_HS.cpp`:
```
Dependency Graph
|-- HomeSpan @ 2.0.0 (License: Unknown, Path: C:\Users\frankonski\Documents\PlatformIO\Projects\LightStrip\lib\HomeSpan)
|   |-- DNSServer @ 3.0.7 (License: Unknown, Path: C:\Users\frankonski\.platformio\packages\framework-arduinoespressif32\libraries\DNSServer)
|   |   |-- ESP32 Async UDP @ 3.0.7 (License: Unknown, Path: C:\Users\frankonski\.platformio\packages\framework-arduinoespressif32\libraries\AsyncUDP)
|   |   |-- WiFi @ 3.0.7 (License: Unknown, Path: C:\Users\frankonski\.platformio\packages\framework-arduinoespressif32\libraries\WiFi)
|   |   |   |-- Networking @ 3.0.7 (License: Unknown, Path: C:\Users\frankonski\.platformio\packages\framework-arduinoespressif32\libraries\Network)
|   |-- ESPmDNS @ 3.0.7 (License: Unknown, Path: C:\Users\frankonski\.platformio\packages\framework-arduinoespressif32\libraries\ESPmDNS)
|   |-- ArduinoOTA @ 3.0.7 (License: Unknown, Path: C:\Users\frankonski\.platformio\packages\framework-arduinoespressif32\libraries\ArduinoOTA)
|   |   |-- Networking @ 3.0.7 (License: Unknown, Path: C:\Users\frankonski\.platformio\packages\framework-arduinoespressif32\libraries\Network)
|   |   |-- Update @ 3.0.7 (License: Unknown, Path: C:\Users\frankonski\.platformio\packages\framework-arduinoespressif32\libraries\Update)
|   |   |-- ESPmDNS @ 3.0.7 (License: Unknown, Path: C:\Users\frankonski\.platformio\packages\framework-arduinoespressif32\libraries\ESPmDNS)
|   |-- WiFi @ 3.0.7 (License: Unknown, Path: C:\Users\frankonski\.platformio\packages\framework-arduinoespressif32\libraries\WiFi)
|   |   |-- Networking @ 3.0.7 (License: Unknown, Path: C:\Users\frankonski\.platformio\packages\framework-arduinoespressif32\libraries\Network)
Building in release mode
```

Any chance to have the basenames in sync?

**Comment by HomeSpan** [comment]
As previously mentioned, when Espressif launched version 3.X of the Arduino-ESP32 library they made a LOT of changes to their code base, including many that were not backwards compatible.  One of the changes they made was to create a globally-scoped  `Network` object that unified their globally-scoped `WiFi` and `ETH` objects. This was actually a very good move since it enabled me to more readily integrate Ethernet support into HomeSpan, and you will see that apart from just a small number of ETH and WiFi-specific calls, HomeSpan now uses the Network object for all communication (hence it works whether using Ethernet or WiFi).

But the one downside to all this is that Espressif also changed their own code-base names, including adding a new `Network.h` header file.  Of course they did not document this anywhere and it took me a week to figure out why HomeSpan would not compile --- my own Network.h file was clashing with the newly-added Arduino-ESP32 Network.h file.  So I changed the name of my Network.h to file Network_HS.h to avoid the conflict.

As for changing the name of my Network.cpp file, I'd rather not make changes to file names for such reasons - I need the flexibility to rename anything at any time in library updates, either because of design changes in HomeSpan, or in response to design changes in the Arduino-ESP32 library, or the IDF itself.  Also, I think it was only by luck that things compiled before the change.  For example, HomeSpan has PSRAM.h, Settings.h, etc. files without corresponding .cpp files.

I think the root of the problem is the way you've configured things in PIO.  According to https://docs.platformio.org/en/latest/librarymanager/ldf.html there are a number of things you can do to address the issue more robustly. One is to use the "deep" option, but it looks like there are other configuration changes you can make to solve the problem more generally so this does not re-surface in the future.

**Comment by frankonski** [comment]
Generally speaking, it would be nice if the whole HomeSpan code base had its own namespace to prevent such conflicts from the get-go, such having a prefix on all filenames & global variables like `hs_` or `hspn_`.

Nevertheless, ideally we can use default build settings (not having to specific `lib_ldf_mode = deep`).

I just tested moving `#include <DNSServer.h>` from `Network.cpp` to `Network_HS.h` and this also resolves the issue. Would you be willing to make this change? I can update the PR.

The definition of "chain" is
> Parses ALL C/C++ source files of the project and follows only by nested includes (#include ..., chain...) from the libraries. It also parses C, CC, CPP files from libraries which have the same name as included header file.

Since currently, `#include <DNSServer.h>` is in a cpp file which does not have the same name as the header file, the cpp file is not parsed, and DNSServer.h is not included by the dependency builder. And it is not found in any nested include either, as only .h files are parsed.

This is why it would be appreciated if my latest suggestion could be implemented (move `#include <DNSServer.h>` from `Network.cpp` to `Network_HS.h`)

**Comment by HomeSpan** [comment]
The problem is that *DNSServer.h* is not used by *Network_HS.h* and has no business being in that file.  As written the current code seems 100% compliant with best-practices. I think the issue is with how you configured PIO.  I assume PIO knows (or should know) the difference between library files and your primary sketch - it should NOT be recompiling everything each time as if was one big program.

The change you suggest above may work for now, but it won't the next time I change the naming conventions of the files, or my headers.  The whole point of a library is that the underlying code structure should not matter.   Though I don't use PIO, it seems that the problem is PIO wrote it's own dependency driver instead of using *gcc* directly, or *make*, or any other tool that's been standardized for decades.  That's fine - PIO claims their method to parse all the files and find dependencies is faster.  But that apparently comes at a cost in that you (A) have to organize your code certain ways.  Alternatively, you can (B) make sure to add the required dependencies to your .ini file, or (C) select "deep" or something similar that causes the tool-chain to properly parse the files to find the dependencies.

To avoid any issues in the future, I suggest you implement the alternatives (B) and/or (C) above.  Method (A) (changing the files structure) is not going to work, especially as the release after I complete 2.1.0 will be related to trying to reduce the size, which inevitably will mean every file name and header file will likely change.

**Comment by MaffooClock** [comment]
I added [a comment](https://github.com/HomeSpan/HomeSpan/discussions/923#discussioncomment-11586450) to discussion #923 before I saw this PR.  Figured I should mention it here in case anyone else is having the same trouble and lands here before seeing the discussion.

**Comment by frankonski** [comment]
> The problem is that DNSServer.h is not used by Network_HS.h and has no business being in that file.
I guess that becomes a coding preference. I'm ok if you prefer to keep things this way.

And I'll stick with Option C (deep) as it is a clean option. Feel free to close this PR.

**Comment by HomeSpan** [comment]
Thanks for the link.  However, I don't have any plans at present to revisit (I may in the future if I ever start using PlatformIO or even just VS Code).

**Pull request closed without merging**
