### PR TITLE
Adding WiFi power levels and free RAM to weblog

### PR DESCRIPTION
**Pull request by frankonski**
Adding WiFi power levels to weblog. Could be useful to someone, somewhere.. Used during discussion #613 to figure out cause of brownouts.

### CODE REVIEW

**Comment by HomeSpan** [comment]
I did not think I closed this - was going to add in next release.  I'll re-open.

**Comment by frankonski** [comment]
@HomeSpan , again, closed on purpose?

**Comment by HomeSpan** [comment]
No, this is an artifact of GitHub.  As part of development I needed to delete/replace the current dev branch.  Apparently GitHub closes PR requests on dev when this happens.  Can you add the PR to the master branch instead?  This should keep things stable as I continue to rework the dev branch (including the need to delete and replace).

**Comment by frankonski** [comment]
Done. PR #657

**Pull request closed without merging**
