### PR TITLE
Added support for pull down control buttons

### PR DESCRIPTION
**Pull request by stzoran1**
See #645

### CODE REVIEW

**Comment by stzoran1** [comment]
If you like this new feature I can update docs before merge. Please let me know.

**Comment by HomeSpan** [comment]
Thanks, but I think it would be more generic to simply add a second optional argument to setControlButton to allow the user to specify the Trigger Type, which could be one of the built-ins, or a complete custom function:

```C++
setControlPin(uint8_t pin, triggerType_t triggerType=TRIGGER_ON_LOW){controlButton=new PushButton(pin, triggerType_t);}
```

I can add this to the next release (in progress at release-1.8.1-dev)

**Comment by stzoran1** [comment]
I completely agree @HomeSpan

**Comment by HomeSpan** [comment]
Completed.  

`homeSpan.setControlPin()` now accepts a *second* optional argument specifying the trigger type using the same logic as SpanButton.  Choices are:

SpanButton::TRIGGER_ON_LOW --- for control pin connected to ground through a pushbutton (the default)
SpanButton::TRIGGER_ON_HIGH --- for control pin connected to VCC through a pushbutton
SpanButton::TRIGGER_ON_TOUCH --- for a control pin connected to a touch sensor (not really recommended for this use)

or you can provide your own trigger function of form  `boolean f(int pin)`  For example, using a lambda function:

```
pinMode(21,OUTPUT);
homeSpan.setControlPin(21, [](int pin)->boolean{ return(digitalRead(pin)); } );
```

is equivalent to:

```
homeSpan.setControlPin(21, SpanButton::TRIGGER_ON_HIGH);
```

Note as per above, if you specify your own trigger function, you need to explicitly configure the pin (or whatever device you are using for the control pin).

Code is updated in 1.8.1-dev branch and will be part of next production release (with documentation updated accordingly).

Thanks again for the suggestion.

**Pull request closed without merging**
