### PR TITLE
Added extra details to weblog webserver.

### PR DESCRIPTION
**Pull request by frankonski**
Display libsodium and MbedTLS version.
Allow specifying a custom stylesheet to start customizing the output.

### CODE REVIEW

**Comment by HomeSpan** [comment]
I like this idea, but rather than add a css style as an extra, defaulted parameter to the end of `webLog.init()` (which forces you to specify all the other parameters), I think it will be more streamlined to create a separate `webLog.style(tableID,style)` method.   I'll add the code to the dev branch and let you know when available to test.

**Comment by HomeSpan** [comment]
The *dev* branch has been updated to include the version numbers of the sodium and mbedTLS libraries in the webLog output.  I also added in a line to show the HomeKit Status as either PAIRED or NOT PAIRED.

For the style sheet, I added a new method `homeSpan.setWebLogCSS(const char *css)` that provides html class-control of the body (class = *bod1*), the first table (class = *tab1*), and the second table (class = *tab2*).  For example, the following shows how to change the background color of the web page and the color of the header text (which is formatted as \<h2\>), change the background color of the first table, and change the colors and format of the second table:

```C++
  homeSpan.setWebLogCSS(".bod1 {background-color:lightyellow;}"
                        ".bod1 h2 {color:blue;}"
                        ".tab1 {background-color:lightgreen;}"
                        ".tab2 {background-color:lightblue;} .tab2 th {color:red;} .tab2 td {color:darkblue; text-align:center;}"
                        );
```                 

Please feel free to give it a try.

**Comment by frankonski** [comment]
Thanks! Your approach definitely makes  more sense than mine. I will give it a try as soon as
* I figure out how to sync (fork) your _dev_ branch (my fork only shows _master_)
* I receive my new ESP32-WROVER this week as I think I fried / bricked my Christmas gift last Monday... I have a support case opened with the vendor, but I don't have a lot of faith in resurrecting it :(

**Comment by frankonski** [comment]
One thing I forgot to mention in my PR: set the page charset to UTF-8: https://github.com/HomeSpan/HomeSpan/pull/563/files#diff-2c54f7f4a7451838ec1143bd95ba7bcd38426be379924b0226d5fcaf576f2e75R1249

Reason is that my HomeSpan display name contains accents, like "Système", which gets incorrectly displayed if you don't set the page to UTF-8.

**Comment by HomeSpan** [comment]
Sorry - forgot about the UTF-8 change.  I just added it to the dev branch and tested to make sure accents are rendered correctly.  Thanks again for these suggestions!

**Comment by frankonski** [comment]
I cherry-picked your changes from the dev branch and added that to my own branch for testing (so I don't test with your dev branch). Changes look good to me, with a simple call:
<code>homeSpan.setWebLogCSS( 
    ".bod1 {background-color:white;}\n"
    ".bod1 h2 {color:navy;}"
    "  th, td {border: 1px solid; padding: 0px 10px 0px; }\n"
    ".tab1 {border-collapse: collapse;}\n"
    ".tab2 {border-collapse: collapse;}\n"
    );
</code>
..  gives me this:
image

So I'm good if you merge your **dev** changes into **main**

**Comment by HomeSpan** [comment]
Excellent.  Note that I use the dev branch for development of all new functions for the upcoming release, and then merge to master when the new release is published.

For now, should we close the pull request?

**Comment by frankonski** [comment]
Yes. I will delete my branch once I see the changes in a new release. Thanks for making the changes!

**Comment by frankonski** [comment]
One more small thing, you could save a few bytes by changing
`char mbtlsv[64];`
to
`char mbtlsv[18];`

From https://arm-software.github.io/CMSIS-mbedTLS/latest/version_8h.html
> The mbed TLS version string will use 18 bytes **AT MOST** including a terminating null byte.

**Comment by HomeSpan** [comment]
Thanks - I'll make that change as well.

**Comment by frankonski** [comment]
Closing, code is in dev branch.

**Pull request closed without merging**
