### PR TITLE
Adding enum for SecuritySystemState values.

### PR DESCRIPTION
**Pull request by frankonski**
Ensures valid values are used, makes code easier to read and maintain.

### CODE REVIEW

**Comment by frankonski** [comment]
For HomeSpan users, this ends up being much more friendly to use and maintain, especially if Apple decides it changes their numerical values for states. Unlikely to happen, but who knows..

Going from:
```
    partitionCurrentState = new Characteristic::SecuritySystemCurrentState(3);  // Sets initial state to disarmed
    partitionCurrentState->setValidValues(3,0,1,3);
    partitionTargetState = new Characteristic::SecuritySystemTargetState(3);    // Sets initial state to disarmed
    partitionTargetState->setValidValues(3,0,1,3);

    switch (partitionCurrentState->getVal()) {
      case 0:
        str = "Armed for Stay";
        break;
      case 1:
        str = "Armed for Away";
        break;
      case 2:
        str = "Armed for Night";
        break;
      case 3:
        str = "Disarmed";
        break;
      case 4:
        str = "ALARM!";
        break;
      default:
        str = "Unknown state";
    }
```
to
```
    partitionCurrentState = new Characteristic::SecuritySystemCurrentState(HSSecuritySystemState::Disarmed);  // Sets initial state to disarmed
    partitionCurrentState->setValidValues(3,Stay,Away,Disarmed);
    partitionTargetState = new Characteristic::SecuritySystemTargetState(HSSecuritySystemState::Disarmed);    // Sets initial state to disarmed
    partitionTargetState->setValidValues(3,Stay,Away,Disarmed);

    switch (partitionCurrentState->getVal()) {
      case HSSecuritySystemState::Away:
        str = "Armed for Away";
        break;
      case HSSecuritySystemState::Night:
        str = "Armed for Night";
        break;
      case HSSecuritySystemState::Stay:
        str = "Armed for Stay";
        break;
      case HSSecuritySystemState::Disarmed:
        str = "Disarmed";
        break;
      case HSSecuritySystemState::Alarm:
        str = "ALARM!";
        break;
      default:
        str = "Unknown state";
    }
```

**Comment by HomeSpan** [comment]
Though this is a good idea, I had planned on adding something more generic to cover all the Characteristics that have a set selection of values.  To make the nomenclature as easy as possible, I thought I'd add an `enum` to the instantiation of each Characteristic in the `Span.h` file.  This would mean the fully scoped enum would be something like Characteristic::SecuritySystemCurrentState.Night, or, in your example above, you could use partitionCurrentState.Night, since the enums would be inherited. 

Since I created a macro to instantiate each Characteristic, I need to first update it so it takes an optional set of "enums".   I was also going to add the descriptions of each enum directly in the code as a tagged comment that would allow the auto-generation of documentation (I already have a simple script that generates the Services table from the code).

Though the code change is modest, it's a reasonable amount of work to go through all the HAP Characteristics, add all the enums, and then the descriptions of each enum (in some cases I may change the HAP description when it is unclear).

Was planning on tackling this after the 1.8.1 release.  Once I update the macro to make it as easy as possible to add enums to Characteristics I'll let you know so you can try it out.

**Comment by phybros** [comment]
+1 for this, it would be nice to have states for OPEN, CLOSED etc for garage doors also, instead of 0, 1 and so on

**Comment by frankonski** [comment]
> Since I created a macro to instantiate each Characteristic, I need to first update it so it takes an optional set of "enums". I was also going to add the descriptions of each enum directly in the code as a tagged comment that would allow the auto-generation of documentation (I already have a simple script that generates the Services table from the code).

Yeah, I noticed you had mastered the art of macros. I was happily impressed when I saw that. I might give a try to your original idea. Note that I'd also like to have this macro create c-style comments (if at all possible) so that when you use VSCode, you have inline documentation. Quite useful.

**Comment by frankonski** [comment]
How is this updated PR? If you like the new style I will update the other .md files modified as part of this PR to make sure when it gets merge (if it does), the updated .md matches the new enums.

For now, it would be used this way:
```
    switch (partitionCurrentState->getVal()) {
      case Characteristic::SecuritySystemState::Away:
        str = "Armed for Away";
        break;
      case Characteristic::SecuritySystemState::Night:
        str = "Armed for Night";
        break;
      case Characteristic::SecuritySystemState::Stay:
        str = "Armed for Stay";
        break;
      case Characteristic::SecuritySystemState::Disarmed:
        str = "Disarmed";
        break;
      default:
        str = "Unknown state";
    }
```

I also added _Leak Status_, _Battery Charging Status_ and _Door State_.

**Comment by HomeSpan** [comment]
I have this section of the code open right now -- I found a way of significantly reducing the memory associated with how the list of required and optional Characteristics for each Service are stored.  Please hold off a bit on any further changes.

**Comment by frankonski** [comment]
> Please hold off a bit on any further changes.
sure can do! Should I just close that PR then?

**Comment by HomeSpan** [comment]
Leave the PR open for now so we'll know to revisit soon.

**Comment by HomeSpan** [comment]
I've updated the 1.8.1-dev branch with enums for all applicable Characteristics.  See *Span.h* for the changes I made to the macro and the list of all constants.

Constants are scoped within each Characteristic.  As such, there are two ways of accessing:

1. provide the fully-qualified name, such as `Characteristic::SecuritySystemTargetState::ARM_STAY`, or
2. if you create a Characteristic of any given type, the constants are automatically inherited. 

Example:

```C++
Characteristic::SecuritySystemTargetState target();
...
if(target.getNewVal()==target.ARM_STAY) {...}   // applicable constants are inherited by instances of a specific Characteristic 
```

This is how it works with pointers:

```C++
Characteristic::SecuritySystemTargetState *target;
...
target=new Characteristic::SecuritySystemTargetState();
...
if(target->getNewVal()==target->ARM_STAY) {...}
```

Note this will not work:

```C++
SpanCharacteristic *target;
...
target=new Characteristic::SecuritySystemTargetState();
...
if(target->getNewVal()==target->ARM_STAY) {...}     // <- fails because target was defined as general SpanCharacteristic
```

But if you use the above construct (as I have done in all the HomeSpan Examples ☹️) you can always use the fully-qualified name:

```C++
SpanCharacteristic *target;
...
target=new Characteristic::SecuritySystemTargetState();
...
if(target->getNewVal()==Characteristic::SecuritySystemTargetState::ARM_STAY) {...}     // always will work
```

I'll probably go back and update all the examples to avoid the generic use of SpanCharacteristic and add in all the constants wherever applicable.

Please feel free to give it a try and let me now how it works.

**Comment by frankonski** [comment]
> Re the constants, one of the tricky part is to figure out a good naming convention, so curious if you find the names easy-to-use.

I think so, yes. I would still add enums for boolean characteristics (MotionDetect) as someone doing a `getVal()` on a variable name called `motionSensor` may want to use `DETECTED`.

And a suggestion: maybe `BATTERY_OK` is better than `NOT_LOW_BATTERY` ?

**Comment by frankonski** [comment]
actually, it won't compile weather when using named or unnamed enum.
```
C:\Users\<hidden>\Documents\Arduino\libraries\HomeSpan\src/HomeSpan.h:613:13: error: invalid conversion from 'int' to 'Characteristic::ContactSensorState::<unnamed enum>' [-fpermissive]
     return(0);       // included to prevent compiler warnings
     
C:\Users\<hidden>\Documents\Arduino\libraries\HomeSpan\src/HomeSpan.h:613:13: error: invalid conversion from 'int' to 'Characteristic::ContactSensorState::state' [-fpermissive]
     return(0);       // included to prevent compiler warnings
```
The fix seems to be to change
```
    return (0);       // included to prevent compiler warnings  
```
to
```
    return T();
```
.. but don't ask me why! ;-)

**Comment by frankonski** [comment]
Maybe this would sound better?
`contact.NO_CONTACT` and `contact.DETECTED`,
`motion.NO_MOTION` and `motion.DETECTED`

instead of `NOT_DETECTED` ?

**Comment by HomeSpan** [comment]
Did this compiler warning just start?  The return(0) has been there for quite a while.

**Comment by frankonski** [comment]
> Did this compiler warning just start? The return(0) has been there for quite a while.

Yes, but I think it showed up only once I started actually using the enum. And it wasn't a warning, it was actually an error preventing the build to complete.
Here is the full error:
```
In file included from C:\Users\<hidden>\Documents\<hidden>\dscHome\dscHome.ino:59:
C:\Users\<hidden>\Documents\Arduino\libraries_renamed\HomeSpan\src/HomeSpan.h: In instantiation of 'T SpanCharacteristic::uvGet(SpanCharacteristic::UVal&) [with T = Characteristic::SecuritySystemTargetState::<unnamed enum>]':
C:\Users\<hidden>\Documents\Arduino\libraries_renamed\HomeSpan\src/HomeSpan.h:774:12:   required from 'void SpanCharacteristic::setVal(T, boolean) [with T = Characteristic::SecuritySystemTargetState::<unnamed enum>; boolean = bool]'
C:\Users\<hidden>\Documents\<hidden>\dscHome\DEV_dscPartition.h:181:69:   required from here
C:\Users\<hidden>\Documents\Arduino\libraries_renamed\HomeSpan\src/HomeSpan.h:613:14: error: invalid conversion from 'int' to 'Characteristic::SecuritySystemTargetState::<unnamed enum>' [-fpermissive]
     return (0);       // included to prevent compiler warnings
```

**Comment by HomeSpan** [comment]
I've been able to reproduce the issue.  It's actually a real problem I need to address as a result of implicit typecasting when using templates that have enum constants.  The line `return(0)` should never be reachable, but I now see why it is when called with the new enum constants.  I'll address and post a fix once I figure out the best solution.

**Comment by HomeSpan** [comment]
I figured out the problem and it turns out the solution is to indeed change `return(0)` to `return((T)0)`.  This line never does get called, but the compiler will complain anyway. Fix is uploaded to 1.8.1-dev.

**Comment by frankonski** [comment]
Compiles fine, runs fine for now with that last fix, and enums seems to be enum-ing just fine. Thanks!

**Comment by frankonski** [comment]
I'm happy with your changes, feel free to close that PR.

**Pull request closed without merging**
